### ISSUE TITLE
Dynmap

### ISSUE THREAD

**Issue by 13E666L13** [Nebula-MC/Recipes#1]
The dynmap has many problems, many players aren't loaded in so it's hard to navigate, please fix.

**Comment by Goosius1** [comment]
- As of SiegeWar 0.4.1 the default dynmap has changed:  Instead of players being visible nearly all the time, but hiding when underground/shadows/dual-wielding etc., the new setup much simpler:  **Whenever a player is in the wilderness or a besieged town, and not in a banner control session, they get hidden.**
- In the old setup, armies had few tactical options, other than simply sending all available soldiers straight at the enemy for everyone to see, and hoping for the best.
- This was a big disadvantage for small armies, and a big advantage for large ones.
- In the new setup, small armies have a better chance, as they can use tactics like ambushes, secret marches, or bringing in unexpected reinforcements.
- The new default setup has many implications for gameplay, for example, and you have to do navigation differently, e.g. using gameworld landmarks and checking F3 to see the co-ordinates you are at,
- The implications are detailed here:   https://github.com/TownyAdvanced/SiegeWar/pull/302

**Comment by kz-n** [comment]
Why has this been made an issue here? This is a repository for Earth Towny recipes.

**Comment by 0xBit-MC** [comment]
Never saw this until now. Let me make a GitHub issues.
